### ISSUE TITLE
WebImageDrop doesn't work properly on Mac OS X Sierra (10.12.1)

### ISSUE THREAD

**Issue by greg6614** [mgarin/weblaf#423]
Hi,

I working with WebImageDrop and under Mac OS X Sierra (10.12.1) i'm not able to drop image inside. I'm using JDK 1.8.0_102 and it's working correctly under Windows 10.

Do you have any suggestion ? 
I Have no error message, just nothing happen.

Thank you.

**Comment by mgarin** [comment]
Sounds like an old issue with D&D that appears from time to time on different systems. I haven't tried Mac OS X Sierra yet, so can't say for sure what is wrong there. It could either be that the system format in which dragged images are presented has changed or that native D&D doesn't get properly connected with Java application which could happen due to multiple reasons.

One more possible issue could be the older `WebImageDrop` version you might be using - it contained a few issues which stopped drop from working properly. You could try out newer version from either of these two sources:
http://weblookandfeel.com/downloads/styling/
https://oss.sonatype.org/content/repositories/snapshots/com/weblookandfeel/
These are builds based on `styling` branch sources which will be the base for v1.2.9 final release. Builds that are currently placed on the site download page are much older builds.

If the issue is still there even with the newer version - the fastest way to find it out what is actually wrong would be running a simple debug on `ImageTransferHandler` (only on newer `styling` branch builds) which is the main `TransferHandler` implementation used within `WebImageDrop` component.

Method that parsed dragged data is `ImageTransferable.getImagesList(...)` - if you would reach this method but it returns empty/null list of images that means that system images format has changed on the newer OS version and I will have to do some adjustments to the code, if you don't reach this method in debug - that means that D&D simply doesn't work, probably in the whole application, or something is blocking it like another `TransferHandler` placed on component that lies on top of that one like glass pane.

**Comment by greg6614** [comment]
Thanks for your answer.
It seems to have a lot changes in v1.2.9, I have to totally remake my code before testing it because I use a lot of WebNotificationPopup which seems to be now rename in WebNotification.

If I remember well, I think that it worked properly on Yosemite. I can try during the day.

So I'll try to remake my code with the new 1.2.9 build from styling branch and then try what you tell me.
I come again ASAP.

**Comment by mgarin** [comment]
> So I'll try to remake my code with the new 1.2.9 build from styling branch and then try what you tell me.
I come again ASAP.

You can try it on a separate small example with just a frame with `WebImageDrop` component so it won't take that much time and won't affect your project.

But if it would indeed work on Yosemite that means they actually changed native dragged image(s) format and I will have to add some Sierra-related code.

**Comment by mgarin** [comment]
And in general - yes, the new v1.2.9 builds contain lots of visual and internal changes for all parts of the library. It is pretty much a major revamp of the code along with the proper styling system introduction that I was planning to add.

If you want to dive deeper into the features of the upcoming v1.2.9 release you could already find some introduction articles on the wiki here describing different new features.

**Comment by greg6614** [comment]
Yes indeed you right, I'll write a small exemple code and tell you what It returns.

**Comment by greg6614** [comment]
Correction: It works on Mavericks, I didn't try under Yosemite

**Comment by greg6614** [comment]
Correction: It works on Mavericks, I didn't try under Yosemite

EDIT : It still doesn't work with v.1.2.9, and I'm not sure how to reach `ImageTransferable.getImagesList(...)`. Through listener on WID component ?

**Comment by mgarin** [comment]
If under "how to reach" you meant the debug - you should be able to debug `ImageTransferable.getImagesList(...)` method directly in any IDE if you have WebLaF source code attached to your project. You can find JAR or ZIP files with sources in the same repositories I have provided above - I would personally recommend using JAR ones as all IDEs will properly detect those as source package.

**Comment by greg6614** [comment]
I have sources attached but I'm not sure to understand how to debug `ImageTransferable.getImagesList(...)` from it using Eclipse.

**Comment by mgarin** [comment]
Simply put a breakpoint in the source code of `ImageTransferable` class and you should hit it if it will be reached in runtime, all the same as with debugging the editable code.

**Comment by greg6614** [comment]
Ok I misunderstood what you tell, I thought that you want me to manually call the function. 

So I debug it and the program correctly pass through the function but the list is empty and it finally return a null value.

**Comment by mgarin** [comment]
Ok, thanks for the info. It seems I will have to get my hands on Mac OS X Sierra to write an additional piece of code that will retrieve files and/or images from the transferable data there.

**Comment by greg6614** [comment]
Thanks for your reply, could you notify me when it's done ? For now I will try to convert my current code from my old weblaf version to the newest. All the components are still there or some of them has been removed ?

**Comment by mgarin** [comment]
I will update this issue as soon as fix is available, so you should receive a notification from GitHub if you are subscribed. Not sure when exactly I will be able to get a newer Mac OS X version running, maybe one of my colleagues will be able to help me out with that.

Regarding the newer version - even if something was removed it simply means that it is obsolete and there is a better tool to do the same thing. Feel free to ask me directly if you are missing something and not sure how to replace it. 

You can use [gitter chat](https://gitter.im/mgarin/weblaf) for asking quick questions instead of this issue tracker as it might be more convenient and simply faster to use. I might also be able to provide answers to simple questions faster there.

**Comment by mgarin** [comment]
I actually found a related bug on the Open JDK tracker:
https://bugs.openjdk.java.net/browse/JDK-8160941

I wonder if that issue is there in the Oracle JDK 1.8.0 u102 build, because if so - we'd have to wait for a JDK fix as the file list would simply be not readable without separators.

**Comment by greg6614** [comment]
Thanks for the info,
He says that it works under JDK 1.9, I'll try if I can use WID component with 1.9.

**Comment by mgarin** [comment]
You can try using JDK 8 earlier than u91 - those shouldn't have this issue yet. And hopefully new update with the fix will soon be released so you can use the latest one.

**Comment by greg6614** [comment]
I tried with JDK 1.8.0_112 which is the most recent version and with JDK 1.8.0_77 and WID still doesn't work. When I debug `ImageTransferable.getImagesList(...)` the List is still empty.

**Comment by mgarin** [comment]
My colleague (who also pointed me at the Open JDK issue) says it worked for him on JDK 8 u65 (and JDK 6/7), but issue is there on JDK 8 u112 and probably on some earlier versions.

**Comment by greg6614** [comment]
He can drop image into WID component under Mac OS Sierra ?

**Comment by mgarin** [comment]
Yep, we just re-checked - you can do it under Mac OS Sierra with JDK 8 u65 with any WebLaF version (even older ones as that part of coded didn't change much), but you cannot do that with JDK 8 u77. So it seems that the bug was introduced somewhere between u65 and u77.

**Comment by greg6614** [comment]
Ok after some tries, the bug seems to has been introduced with JDK 8u74 because it works with update 73 but not with update 74.
I will roll back under JDK 8u73 waiting for a new working JDK version.

Thank you very much for your help.

**Comment by mgarin** [comment]
I'll keep this issue open until JDK bug is resolved, hopefully in 8u122.
Bug link for reference: https://bugs.openjdk.java.net/browse/JDK-8160941

**Comment by greg6614** [comment]
If I have any info about the release date of this new JDK version I'll post them here.
I hope it will soon be released.
PS : The new demo of WebLaf v1.2.9 is pretty cool, I really like the new style it's clearer and it's now easy to find components. Just go on.

**Comment by mgarin** [comment]
Thanks! There are still quite a few things I want to improve in the demo, but it will get better and will get much more examples than there are right now. So far it is simply a playground for testing new stuff and how things work together in the new branch, but it will get more solid before the release.

**Comment by mgarin** [comment]
Just marking that this issue has a workaround - can be avoided by using JDK 8 u73 and earlier.
